import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { text } = await req.json();
    if (!text || typeof text !== "string" || text.trim().length < 20) {
      return new Response(JSON.stringify({ error: "Please provide at least 20 characters of text to analyze." }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY is not configured");

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          {
            role: "system",
            content: `You are an expert AI text forensics analyst. Analyze the given text and determine whether it was written by a human or generated by AI. 

You MUST respond by calling the analyze_text function with your analysis.

Consider these factors:
- Vocabulary diversity and word choice patterns
- Sentence structure variation and complexity
- Presence of personal voice, opinions, or emotional expression
- Repetitive patterns or formulaic phrasing typical of AI
- Use of filler words, colloquialisms, or informal language (more human)
- Overly polished, generic, or neutral tone (more AI)
- Logical flow and coherence patterns
- Presence of minor imperfections or typos (more human)

Be precise and analytical. Provide a confidence score from 0-100 where:
- 0 = Definitely human-written
- 100 = Definitely AI-generated`
          },
          {
            role: "user",
            content: `Analyze this text for AI generation:\n\n"${text.slice(0, 5000)}"`
          }
        ],
        tools: [
          {
            type: "function",
            function: {
              name: "analyze_text",
              description: "Return the AI detection analysis results",
              parameters: {
                type: "object",
                properties: {
                  verdict: { type: "string", enum: ["AI-Generated", "Human-Written", "Mixed/Uncertain"] },
                  confidence: { type: "number", description: "Confidence score 0-100 (0=human, 100=AI)" },
                  summary: { type: "string", description: "2-3 sentence summary of the analysis" },
                  indicators: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        label: { type: "string" },
                        detail: { type: "string" },
                        signal: { type: "string", enum: ["ai", "human", "neutral"] }
                      },
                      required: ["label", "detail", "signal"],
                      additionalProperties: false
                    },
                    description: "4-6 key indicators found in the text"
                  }
                },
                required: ["verdict", "confidence", "summary", "indicators"],
                additionalProperties: false
              }
            }
          }
        ],
        tool_choice: { type: "function", function: { name: "analyze_text" } },
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(JSON.stringify({ error: "Rate limit exceeded. Please try again in a moment." }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (response.status === 402) {
        return new Response(JSON.stringify({ error: "AI credits exhausted. Please add credits to continue." }), {
          status: 402,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      const t = await response.text();
      console.error("AI gateway error:", response.status, t);
      throw new Error("AI analysis failed");
    }

    const data = await response.json();
    const toolCall = data.choices?.[0]?.message?.tool_calls?.[0];
    if (!toolCall) throw new Error("No analysis result returned");

    const result = JSON.parse(toolCall.function.arguments);

    return new Response(JSON.stringify(result), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("analyze-text error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Analysis failed" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
