import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Shield, Scan, RotateCcw, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import ConfidenceGauge from "@/components/ConfidenceGauge";
import AnalysisIndicator from "@/components/AnalysisIndicator";
import ScanningOverlay from "@/components/ScanningOverlay";

interface AnalysisResult {
  verdict: string;
  confidence: number;
  summary: string;
  indicators: { label: string; detail: string; signal: "ai" | "human" | "neutral" }[];
}

const SAMPLE_TEXTS = [
  `The morning sun cast long shadows across the kitchen floor as I fumbled with the coffee maker, still half-asleep. My cat, predictably, had knocked over the plant on the windowsill again — third time this week. I really need to move that thing, but honestly? I kind of like the chaos. There's something comforting about the mess of it all, you know?`,
  `Artificial intelligence has fundamentally transformed the landscape of modern technology, offering unprecedented capabilities in data processing, pattern recognition, and automated decision-making. These advancements have enabled organizations to optimize their operational efficiency, enhance customer experiences, and drive innovation across various sectors of the global economy.`,
];

const Index = () => {
  const [text, setText] = useState("");
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const { toast } = useToast();

  const analyze = async () => {
    if (text.trim().length < 20) {
      toast({ title: "Too short", description: "Please enter at least 20 characters.", variant: "destructive" });
      return;
    }

    setIsAnalyzing(true);
    setResult(null);

    try {
      const resp = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/analyze-text`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
        },
        body: JSON.stringify({ text }),
      });

      if (!resp.ok) {
        const err = await resp.json();
        throw new Error(err.error || "Analysis failed");
      }

      const data: AnalysisResult = await resp.json();
      setResult(data);
    } catch (e: any) {
      toast({ title: "Error", description: e.message, variant: "destructive" });
    } finally {
      setIsAnalyzing(false);
    }
  };

  const reset = () => {
    setText("");
    setResult(null);
  };

  return (
    <div className="min-h-screen bg-background relative overflow-hidden">
      {/* Background grid pattern */}
      <div
        className="absolute inset-0 opacity-[0.03]"
        style={{
          backgroundImage: `linear-gradient(hsl(180 100% 45%) 1px, transparent 1px), linear-gradient(90deg, hsl(180 100% 45%) 1px, transparent 1px)`,
          backgroundSize: "60px 60px",
        }}
      />

      <div className="relative z-10 max-w-3xl mx-auto px-4 py-12 md:py-20">
        {/* Header */}
        <motion.div
          className="text-center mb-10"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <div className="inline-flex items-center gap-2 mb-4 px-3 py-1.5 rounded-full border border-border bg-secondary/50">
            <Shield className="w-4 h-4 text-primary" />
            <span className="text-xs font-mono text-muted-foreground uppercase tracking-widest">
              AI Detection Engine
            </span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-3">
            <span className="text-gradient-primary">AuthentiCheck</span>
          </h1>
          <p className="text-muted-foreground max-w-lg mx-auto">
            Paste any text below to analyze whether it was written by a human or generated by AI.
          </p>
        </motion.div>

        {/* Input area */}
        <motion.div
          className="relative mb-6"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
        >
          {isAnalyzing && <ScanningOverlay />}
          <Textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="Paste your text here to analyze..."
            className="min-h-[200px] bg-card border-border font-mono text-sm resize-none focus:ring-1 focus:ring-primary/50 focus:border-primary/50 placeholder:text-muted-foreground/40"
            disabled={isAnalyzing}
          />
          <div className="absolute bottom-3 right-3 text-xs font-mono text-muted-foreground/50">
            {text.length} chars
          </div>
        </motion.div>

        {/* Sample texts */}
        {!result && !isAnalyzing && (
          <motion.div
            className="flex flex-wrap gap-2 mb-6 justify-center"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3 }}
          >
            <span className="text-xs text-muted-foreground font-mono mr-1 self-center">Try:</span>
            {SAMPLE_TEXTS.map((sample, i) => (
              <button
                key={i}
                onClick={() => setText(sample)}
                className="text-xs font-mono px-3 py-1.5 rounded-md border border-border bg-secondary/30 text-muted-foreground hover:text-primary hover:border-primary/30 transition-colors"
              >
                <FileText className="w-3 h-3 inline mr-1" />
                Sample {i + 1}
              </button>
            ))}
          </motion.div>
        )}

        {/* Action buttons */}
        <div className="flex justify-center gap-3 mb-10">
          {!result ? (
            <Button
              onClick={analyze}
              disabled={isAnalyzing || text.trim().length < 20}
              className="bg-primary text-primary-foreground hover:bg-primary/90 font-mono gap-2 px-6"
              size="lg"
            >
              {isAnalyzing ? (
                <>
                  <Scan className="w-4 h-4 animate-spin" />
                  Analyzing...
                </>
              ) : (
                <>
                  <Scan className="w-4 h-4" />
                  Analyze Text
                </>
              )}
            </Button>
          ) : (
            <Button
              onClick={reset}
              variant="outline"
              className="font-mono gap-2 border-border hover:border-primary/30 hover:text-primary"
              size="lg"
            >
              <RotateCcw className="w-4 h-4" />
              Analyze Another
            </Button>
          )}
        </div>

        {/* Results */}
        <AnimatePresence>
          {result && (
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.5 }}
              className="space-y-6"
            >
              {/* Gauge */}
              <div className="flex justify-center">
                <div className="p-8 rounded-2xl border border-border bg-card/80 backdrop-blur-sm" style={{ boxShadow: "var(--shadow-glow)" }}>
                  <ConfidenceGauge confidence={result.confidence} verdict={result.verdict} />
                </div>
              </div>

              {/* Summary */}
              <motion.div
                className="p-4 rounded-lg border border-border bg-card/60"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.8 }}
              >
                <h3 className="text-xs font-mono uppercase tracking-wider text-muted-foreground mb-2">Analysis Summary</h3>
                <p className="text-sm text-foreground leading-relaxed">{result.summary}</p>
              </motion.div>

              {/* Indicators */}
              <div>
                <h3 className="text-xs font-mono uppercase tracking-wider text-muted-foreground mb-3">Key Indicators</h3>
                <div className="grid gap-2">
                  {result.indicators.map((ind, i) => (
                    <AnalysisIndicator key={i} indicator={ind} index={i} />
                  ))}
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};

export default Index;
